### ISSUE TITLE
Implement MVP

### ISSUE THREAD

**Issue by tmattio** [tmattio/spin#1]
Meta issue containing the list of things to implement to arrive at a working prototype:

**Cloning**
- [x] `spin new` clones `spin-templates` if not already in the cache dir or if not up to date
- [x] `spin ls` clones `spin-templates` if not already in the cache dir or if not up to date
- [x] `spin new` checks if the template is a local path before cloning (and after checking in list of official templates)
- [x] `spin new` takes a `--default` option that will not prompt the user for config if they have a default value

**Templates**
- [x] Read configuration file and prompt user for configuration values
- [x] Copy the template in the path and change files names and content using template engine
- [x] Filter `camel_case`
- [x] Filter `snake_case`

**Generators**
- [x] Read config file for generator
- [x] Generate new files from templates
- [x] Create generator for subcommands for cli template

**Templates**
- [ ] lib
- [x] ppx
- [x] cli
- [x] react
- [x] CI/CD for spin-template

**Release**
- [x] Release with npm (github registry?)
- [x] Release with script
- [x] Release with brew

**Comment by dylanirlbeck** [comment]
@tmattio Do you need any help setting up the `lib` template? I've done a bit of work with publishing libraries for BuckleScript and Reason native, so I might be able to contribute. Just let me know!

**Comment by tmattio** [comment]
Hi @dylanirlbeck, thanks a lot for offering your help!

The reason I haven't pushed the `lib` template yet is because the templates were lacking support for Opam. It didn't make sense to me to create a `lib` template without being able to release it on Opam, so I've tackled it first. I'm almost done with it, and the `lib` template will be pushed in `spin-templates` at the same time.

You can follow the PR here: https://github.com/tmattio/spin-templates/pull/9

That being said, if you want to contribute, any help to review/test the `lib` template (or any other template) on the PR above would be welcome!
