### ISSUE TITLE
change default license?

### ISSUE THREAD

**Issue by ghost** [tmattio/spin#100]
Is it okay if I send a PR to change the default license in you templates to agpl?

**Comment by tmattio** [comment]
Hi @kanishka-work,

Thanks for the suggestion. I don't think changing the default license of the templates would be a good solution: lots of users probably prefer MIT as the default license.

However, I'd very much welcome a PR to offer a choice of license as a configuration of the templates. Here's a list of license most used in Opam packages, from Drom:
https://github.com/OCamlPro/drom/blob/0fc2b8e8ac69b87ca3e4703d044f1249bf02d8dc/src/drom_lib/license.ml#L15

**Comment by ghost** [comment]
I will reopen a little later, if I expect to actively work on this. Probably won't get to it for a while.
