### ISSUE TITLE
Use dune runtest for rely

### ISSUE THREAD

**Issue by wokalski** [tmattio/spin#101]
In order to support colored display `dune` needs to be called with `--no-buffer` (`esy dune runtest --no-buffer`)

**Comment by tmattio** [comment]
Hey @wokalski,

Thanks for the issue! I've just tried `esy dune runtest --no-buffer` in a newly generated `bin` project, and the output is not colored. Not sure why, but nonetheless, definitely onboard to use `dune runtest` instead of the executable - I'll investigate more 🙂

**Comment by wokalski** [comment]
Interesting. I do get colors 😢. Maybe you either do set the Pastel option OR have the env variable set. I forgot the name of either though so I only remember "pastel option" and "env variable".
