### ISSUE TITLE
Add verbose argument to display git logs

### ISSUE THREAD

**Issue by tmattio** [tmattio/spin#16]

**Comment by citizen428** [comment]
Do you mean a verbose argument to `spin` itself, which determines whether or not we keep the git output like this?

```reasonml
      ~stdout=Lwt_process.(`Dev_null),
```

If yes, I can do that.

**Comment by tmattio** [comment]
Exactly yes!

Also, the `git clone` command outputs everything to stderr, so with a verbose mode we could remove the redirection of stderr to `/dev/null` for this specific command.

We could also change the default behaviour of the post install commands in the templates to not write to stdout by default.

I saw this as an opportunity to improve the `cli` template, so I wanted to spend some time thinking about the best way to implement this. I'd be very happy to accept a simple solution, but just FYI if you want to look into it, here are some considerations I had in mind:

- How can we provide the value with an env variable as well (the order of priority would be `env variable -> cli argument -> default value`)
- What is the best way to add arguments common to all sub-commands, while conserving the sub-commands separation, to use with `spin gen cmd`
- Can we create common arguments with a modular design? This would allow us to create a generator for the arguments (e.g. `spin gen arg`)

Thanks a lot for contributing to Spin, let me know if I can do anything to help :)

**Comment by citizen428** [comment]
Great, thanks for the extra context/info 😃 

Regarding the other considerations you mentioned:  maybe it's worth splitting that into a separate issue. One — a verbose flag — is narrowly scoped and immediately useful to some people, the other may take a bit to get right.

**Comment by tmattio** [comment]
Good suggestion, just created #39 for the template related work.
Thanks!

**Comment by tmattio** [comment]
Done in #74
