### ISSUE TITLE
Can't install on mac os 10.15

### ISSUE THREAD

**Issue by curlrain** [tmattio/spin#22]
`spin ls`

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/fabien/.npm-packages/bin/spin (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/fabien/.npm-packages/bin/spin (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by tmattio** [comment]
@curlrain Thanks for the bug report!

Can you paste the output of the following commands here:

```
uname -a
sw_vers -productVersion
npm --version
```

**Comment by curlrain** [comment]
`Darwin MacBook-Pro-15.local 17.7.0 Darwin Kernel Version 17.7.0: Fri Oct  4 23:08:59 PDT 2019; root:xnu-4570.71.57~1/RELEASE_X86_64 x86_64`

`10.13.6`

`6.7.0`

**Comment by tmattio** [comment]
Looking around for similar issues and it seems to be related to a client configuration.

Could you try to update/reinstall your xcode distribution:
```
xcode-select --install
```

If this doesn't work, could you try cloning the repository and see if you can compile the code?

Once downloaded, you can run:
```
npm -g i @esy-nightly/esy
esy install
esy build
```

**Comment by tmattio** [comment]
Will close for now as I think the error is caused by the client environment. Please feel free to re-open if you want help in debugging this.
