### ISSUE TITLE
Binary error on linux (debian)

### ISSUE THREAD

**Issue by kritchie** [tmattio/spin#24]
I'm getting a binary exec format error while trying to run this on Debian.

### System configuration

```
Linux debian 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux
```

### Steps

Here's that I did: 

1. Manually download https://github.com/tmattio/spin/releases/download/v0.4.1/spin-linux-x64.zip
2. Unzip it
3. `chmod +x spin` 
4. `./spin`

### Error

Here's the error I'm getting:

```
bash: ./spin: cannot execute binary file: Exec format error
```

### Extras

After running `file` command, looks like this exec was built for MacOS

```
spin: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE>
```

**Comment by tmattio** [comment]
Thanks for opening an issue and all the details!

Your diagnostic was correct: we were releasing macOS's binaries for Linux. You can try again with the version 0.4.2, it should be fixed.

**Comment by tmattio** [comment]
Going to close this, assuming the install is ok now. Feel free to re-open if this didn't solve the problem.
