### ISSUE TITLE
esy start failing on bootstrap

### ISSUE THREAD

**Issue by idkjs** [tmattio/spin#26]
After bootstrapping with `spin new native tdlib-reason`, `esy start` is failing:

```sh
Happy hacking!
➜  GitHub cd tdlib-reason
➜  tdlib-reason esy install
info install 0.5.8 (using package.json)
➜  tdlib-reason esy build
info esy build 0.5.8 (using package.json)
➜  tdlib-reason esy test
Running 1 test suite
 PASS  my first test suite

Test Suites: 0 failed, 1 passed, 1 total
Tests:       0 failed, 1 passed, 1 total
Time:        < 1ms

➜  tdlib-reason esy start
error: unable to resolve command: tdlib-reason.exe
```

Did I miss a step? Thanks.

Nice work here @tmattio! Thanks for sharing it.

**Comment by tmattio** [comment]
Hi @idkjs!

Thanks for trying out Spin!
I've pushed a fix in the native template for this, let me know if that works for you now :)

**Comment by idkjs** [comment]
Works. 

```sh
Happy hacking!
➜  GitHub spin-test/
➜  spin-test esy i
info install 0.6.0 (using package.json)
➜  spin-test esy b
info esy build 0.6.0 (using package.json)
➜  spin-test esy t
error: unable to resolve command: t

esy: exiting due to errors above
➜  spin-test esy test
Running 1 test suite
 PASS  my first test suite

Test Suites: 0 failed, 1 passed, 1 total
Tests:       0 failed, 1 passed, 1 total
Time:        < 1ms

➜  spin-test esy start
Hello World
```

**Comment by idkjs** [comment]
Unrelated so didn't want to open a new issue. How did you make your demo image on the readme? Its really well done. Thanks.

**Comment by tmattio** [comment]
@idkjs It's a combination of two scripts:

- [scripts/demo-emulate.sh](https://github.com/tmattio/spin/blob/master/scripts/demo-emulate.sh)

Emulates keyboard input on the shell, so you don't have to type the commands yourself.

- [scripts/demo-record.sh](https://github.com/tmattio/spin/blob/master/scripts/demo-record.sh)

Records what's happening on the CLI and save it it a SVG file.

To record the CLI, I use [termtosvg](https://github.com/nbedos/termtosvg), but a lot of people use [asciinema](https://github.com/asciinema/asciinema) and a converter such as [svg-term](https://github.com/marionebl/svg-term).

You can check [`fnm`](https://github.com/Schniz/fnm)'s demo which uses the later. I actually based my scripts from `fnm`'s.

**Comment by idkjs** [comment]
@tmattio thank you, sir.
