### ISSUE TITLE
Upper vs. lower case

### ISSUE THREAD

**Issue by jdeisenberg** [tmattio/spin#31]
When I created a ReasonML project with `spin new native SpinTest`, file names become all lower case (`spintest_app.re`, for example). ReasonML modules should begin with upper case. Is there some way to preserve the capitalization that I entered for the project name when prompted:

```
Project name: SpinTest
Project slug: [spintest] 
```

**Comment by tmattio** [comment]
Hi @jdeisenberg, thanks a lot for trying out Spin and opening an issue!

One of Spin's goals is to bridge the gap between OCaml and Reason. To follow this guidelines, I want to use the same naming conventions for the OCaml syntax and the Reason syntax.

I wrote a bit about it here: https://github.com/tmattio/spin/blob/master/docs/naming-conventions.md

I've also made some research on what people are using in the OCaml and Reason communities and I have put some thoughts here: https://github.com/tmattio/spin/issues/12

I know a lot of people would prefer to use camel case for Reason as it is the most commonly used convention in the community. However the conventions seem to change quickly, and I have seen a lot of different conventions used. To quote myself from the above link:
> if it appears that using a different naming conventions seems better in the future, nothing is preventing us from changing it

I'm going to close this for now, hoping this clarifies why the files are normalized this way. Feel free to re-open if you feel that we should continue the discussion.
