### ISSUE TITLE
Char.code not found

### ISSUE THREAD

**Issue by jdeisenberg** [tmattio/spin#32]
I created a new project:

```
reasonlab> spin new native spintest
📡  Updating official templates.
Done!

Project name: spintest
Project slug: [spintest] 
Description: [] 
Name of the author: J D Eisenberg
Github username: jdeisenberg
Which syntax do you use?
1 - Reason
2 - OCaml
Choose from (1, 2): 1

🏗️  Creating a new native in spintest
Done!

🎁  Installing packages. This might take a couple minutes.
[snip lots of lines of install output]
Done!
[snip more lines of install output]
🎉  Success! Created the project at spintest
```

Then modified `bin/spintest_app.re` to read as follows:

```
open Spintest;

/** Main entry point for our application. */
let s = "abcde";
let c = String.get(s, 0); 
let n = Char.code(c);
let () = Stdio.Out_channel.print_endline @@ Utils.hello();
```

Then attempted to build the project:

```
spintest> esy build
info esy build 0.6.0 (using package.json)
      ocamlc bin/.spintest_app.eobjs/byte/spintest_app.{cmi,cmo,cmt} (exit 2)
(cd /home/david/reasonlab/spintest/_esy/default/store/b/spintest-4245a00c/default && /home/david/.esy/3/i/ocaml-4.8.1000-e74c5c0d/bin/ocamlc.opt -open Base -g -bin-annot -I bin/.spintest_app.eobjs/byte -I /home/david/.esy/3/i/opam__s__base-opam__c__v0.13.0-10f912a7/lib/base -I /home/david/.esy/3/i/opam__s__base-opam__c__v0.13.0-10f912a7/lib/base/base_internalhash_types -I /home/david/.esy/3/i/opam__s__base-opam__c__v0.13.0-10f912a7/lib/base/caml -I /home/david/.esy/3/i/opam__s__base-opam__c__v0.13.0-10f912a7/lib/base/shadow_stdlib -I /home/david/.esy/3/i/opam__s__sexplib0-opam__c__v0.13.0-c49ef5df/lib/sexplib0 -I /home/david/.esy/3/i/opam__s__stdio-opam__c__v0.13.0-b84fea6e/lib/stdio -I lib/.Spintest.objs/byte -I lib/.Spintest.objs/native -no-alias-deps -o bin/.spintest_app.eobjs/byte/spintest_app.cmo -c -impl bin/spintest_app.re.ml)
# Unformatted Error Output:
# File "bin/spintest_app.re", line 6, characters 8-17:
# Error: Unbound value Char.code

ERROR  bin/spintest_app.re:6 8-17 

3 ┆ /** Main entry point for our application. */
4 ┆ let s = "abcde";
5 ┆ let c = String.get(s, 0);
6 ┆ let n = Char.code(c);
7 ┆ let () = Stdio.Out_channel.print_endline @@ Utils.hello();

The value named Char.code can't be found. Could it be a typo?

error: command failed: 'refmterr' 'dune' 'build' '-p' 'spintest' (exited with 1)
esy-build-package: exiting with errors above...
error: build failed with exit code: 1
  
esy: exiting due to errors above

```

This error does not occur with the same code in the `hello-reason` template from https://github.com/esy-ocaml/hello-reason.git

**Comment by citizen428** [comment]
Spin uses [Base](https://opensource.janestreet.com/base/) instead of OCaml's standard library, so it's `Char.to_int c`.

<img width="369" alt="Screen Shot 2020-01-18 at 12 18 34" src="https://user-images.githubusercontent.com/47985/72659080-0a6b7d80-39b2-11ea-907b-ee21c28cf305.png">

**Comment by tmattio** [comment]
Hey @jdeisenberg, thanks for opening this issue!

@citizen428 is right, Spin uses Base as a standard library.

OCaml's standard library being minimalist, people tend to use other standard libraries (Containers, Batteries, Base, Core, etc.)

One design principle that I follow with Spin is convention over configuration. The templates are therefore opiniated. Having the same standard library for all the templates helps to achieve this goal. One thing I am missing when working with OCaml, compared to languages such as Elixir for instance, is to be able to read the source of any project and be confortable with the structure and libraries being used.

Transposed to Spin, I would like to be able to jump on any Spin-generated project and be confortable with the structure and libraries used. I'm planning on writing more about this.

I am going to close this hoping this answers your question.

Thanks!
