### ISSUE TITLE
Running offline after installation crashes

### ISSUE THREAD

**Issue by Dean177** [tmattio/spin#34]
I installed spin, then later whilst I was offline tried to generate a new project:

```sh
spin new cli error-example
```

But this cased an exception to be raised.

```
📡  Downloading official templates.
Done!

😱  Ooops, an unknown error occured. You can file a bug reports at https://github.com/tmattio/spin.
Here is the stack trace in case it helps:

spin: internal error, uncaught exception:
      (Sys_error
        "/Users/deanmerchant/.cache/spin/spin-templates: No such file or directory")
      Raised by primitive operation at file "lib/template_official.re", line 24, characters 2-24
      Called from file "lib/source.re", line 28, characters 20-43
      Called from file "bin/commands/cmd_new.re", line 13, characters 15-41
      Called from file "lib/errors.re", line 10, characters 5-11
      Re-raised at file "lib/errors.re", line 76, characters 4-15
      Called from file "bin/commands/cmd_new.re", line 49, characters 4-84
      Called from file "cmdliner_term.ml", line 25, characters 19-24
      Called from file "cmdliner.ml", line 117, characters 32-39
```

It looks like there are two issues:
- In `template_official.re` `"Done"!` gets printed regardless of the clone succeeding.
- Spin needs to be online the first time it is run.

**Comment by tmattio** [comment]
Hi @Dean177, thanks a lot for trying out Spin and opening an issue.

I'll look into fixing the `Done!` notification when an error occurs.

Spin does not currently support offline usage, even if you already used it once, as it will try to update the official templates every time you run a command. Supporting offline usage is on my to do list, I'll look into it as soon as I have time (currently travelling, so in a week or so).

Thanks!
