### ISSUE TITLE
Evaluate Tablecloth as standard library

### ISSUE THREAD

**Issue by citizen428** [tmattio/spin#43]
As mentioned in #12:

> One goal of Spin is to reduce the gap between OCaml and Reason ecosystems.

[Tablecloth](https://github.com/darklang/tablecloth) aims to provide a consistent standard library between BuckleScript and Reason Native. As such it addresses the concerns mentioned in the above linked issue. Should we explore the feasibility of Tablecloth as standard library for Spin? Or make it an option during `spin new`?

**Comment by tmattio** [comment]
Hey @citizen428!

I wanted to share a few thoughts on this and I've been procrastinating to write them down 😄 
Really appreciate the suggestion - will follow up on this soon!

**Comment by dylanirlbeck** [comment]
Just wanted to pitch in here.

Tablecloth hasn't had a new release in about ~8 months, if I remember correctly. Paul has just been extremely busy with Dark. That said, there's a new standard library (that forked Tablecloth and has been adding to it, with docs as well) that hasn't had an official release, but will soon. 

That library lives at https://github.com/dean177/reason-standard. Check it out!
