### ISSUE TITLE
Reduce redundencies of templates

### ISSUE THREAD

**Issue by Et7f3** [tmattio/spin#45]
Here is a example: https://github.com/tmattio/spin-templates/blob/master/cli/template/.gitignore this file is in each template so if one update one template it might also have to update other template. For instance the [.gitignore proposed by GitHub](https://github.com/github/gitignore/blob/master/OCaml.gitignore). We can miss it easily. It would be cool if we can have a base template and override it: like adding deps. Some base template could be https://github.com/esy-ocaml/hello-reason

For instance: https://github.com/tmattio/spin-templates/blob/master/cli/template/package.json#L18 this command build in release mode even for dev or peerDependencies are useless now ? we have resolutions in esy.

**Comment by tmattio** [comment]
Hi @Et7f3, thanks a lot for opening an issue!

I agree that there are a lot of duplication in the templates, it would be useful to have a base template. I've been thinking of a few solutions and I am not sure how to solve this without introducing a lot of additional complexity. Will keep thinking about it, but maybe I'll wait for this issue to become more painful before addressing it (i.e. when we have more official templates and the duplication becomes nonsensical)

Thanks for the suggestion on the Esy package file! Just saw your commit (https://github.com/esy-ocaml/hello-reason/commit/0ea995aef70b4bdcd44ae12c7b68a923226cb760) on hello-reason. Will look into bringing the templates up to date!

**Comment by tmattio** [comment]
One idea could be to add an `extend` stanza in the template.
It would have two fields:
- `source` - The source of the template to extend
- `except` - A list of file pattern to ignore when extending.

When using the extend stanza, the prompt configs would be merged, all other stanza in the base template would be ignored (simple way to avoid conflicts), the base template would first be generated without the files matching the except field. Then, the template to generate would be used and overwrite any file that have the same filepath.

**Comment by tmattio** [comment]
Done in #74
