### ISSUE TITLE
Question on `.spin` file

### ISSUE THREAD

**Issue by idkjs** [tmattio/spin#47]
Does the `.spin` file have a purpose after the project is set up?

Can we do something like run `spin` in the root and it reads the `.spin` file to execute? 

Never seen a `.spin` extension before. Thanks for any insight.

**Comment by tmattio** [comment]
Hi @idkjs!

The `.spin` file is used for the generators. To be able to list and use the generators specific to the template you used to generate the project, Spin needs to have access to the information present in this file.

Granted, the generators are not a prominent feature at the moment, but I expect they will become very useful for the web server templates (think `mix ecto.gen.schema` but for OCaml/Reason!).

**Comment by idkjs** [comment]
Thanks for that. So is that just a here thing or is there a `.spin` project somewhere? I saw [Propeller Spin](https://www.parallax.com/downloads/propeller-tool-software-windows-spin-assembly) but I dont think that is it.

**Comment by tmattio** [comment]
Yes, nothing to do with Propeller Spin, it's a format defined by Spin that I'll document at some point 🙂
