### ISSUE TITLE
Add warning message when no config file is found

### ISSUE THREAD

**Issue by tmattio** [tmattio/spin#50]
The templates are becoming really heavy on the prompts... To cope with that, we added a `spin config` command that allows users to configure a global context so that they can skip general prompts such as their names.

However, a first time user might not know about `spin config` and be discouraged to use Spin due to the time it takes to create a new project.

We could add a warning to the users if no global configuration file is found to incentivize them to create one which will give them a better UX of Spin.

**Comment by citizen428** [comment]
I'm working on this.

**Comment by tmattio** [comment]
Fixed in #54
