### ISSUE TITLE
Support cli with no subcommands

### ISSUE THREAD

**Issue by tmattio** [tmattio/spin#51]
There are two types of CLIs a user might want to create:

- A single command, with arguments and options, such as `curl`
- A multi-command CLI, with subcommands which themselves have arguments and options, such as `git`

The CLI template currently generates the second option, but it should allow the user to build a single command as well.

This can be added as an new template option when configuring the project.

**Comment by citizen428** [comment]
I just started a single command CLI from the template and I didn't think it was particularly geared towards multi-command apps. To clarify, what would the differences between the two templates be exactly?

**Comment by tmattio** [comment]
By multi-command CLI, I mean CLIs such as `git` or `aws`. You cannot use the command alone, you need to use one of the subcommand, which themselves have their own arguments and options.

A single command CLI would be closer to `curl`, or `wget` for instance, where you can use the command alone by adding the arguments and options directly.

The current templates is geared towards multi-command apps because it comes with a command and sub-command (`hello`) by default. There is also a generator for subcommands which does not make sense if you are developping a single-command CLI.

The alternative would come without the subcommand, and would not list the sub-command as a supported generator.

**Comment by citizen428** [comment]
@tmattio I'm not sure when I get around to this, so I unassigned myself for the time being in case someone else wants to pick it up.

**Comment by tmattio** [comment]
Closing this, for now. If someone is interested in having this, I'll re-open.
