### ISSUE TITLE
workflow/release.yml seems to fail due a __dirname missing

### ISSUE THREAD

**Issue by davesnx** [tmattio/spin#57]
It fails on getting "Get Esy binary path".

Here's an example: https://github.com/davesnx/styled-ppx/runs/492428441?check_suite_focus=true

**Comment by tmattio** [comment]
Hi @davesnx!

Thanks for opening the issue. From what I can see, you changed the default binary name of the ppx from `styled-ppx.exe` to `styled-ppx`. 

The CI/CD script tries to get the path of the binary with this call:
```
s=$(pwd); d=$(dirname $(esy x which styled-ppx.exe));
```

So you'll also need to change that to:
```
s=$(pwd); d=$(dirname $(esy x which styled-ppx));
```

**Comment by tmattio** [comment]
While I have you here, I'd also like to say I'm very happy to see Spin being used to create a PPX! If you have any feedback or ideas on the PPX template, don't hesitate to share them 😄

**Comment by davesnx** [comment]
Ye, was a silly mistake :,(

Maybe we could go into Discord?
