### ISSUE TITLE
Use stricter warnings and errors in templates?

### ISSUE THREAD

**Issue by johnridesabike** [tmattio/spin#76]
This is opinionated, but I think there's a wide agreement that more warnings is better. 

[Here's one recommendation a lot of people follow:](https://dev.to/yawaramin/ocaml-reasonml-best-practice-warnings-and-errors-4mkm)

BuckleScript's bsconfig.json
```json
{
  ...
  "warnings": {
    "number": "+A-48",
    "error": "+A-3-44-102"
  }
  ...
}
```
Dune's dune file
```
(library
  ...
  (flags (:standard -w +A-48 -warn-error +A-3-44))
  ...)
```

(Personally, I also disable warning 42 in my projects since some libraries aren't compatible with it.)

Although this is opinionated, I think having a stricter default and letting the user opt-out of that is preferable.

**Comment by tmattio** [comment]
Thanks for the suggestion @johnridesabike!

I agree that generally, the more warnings, the better. I'm preparing a new release of Spin and will include this in it. I think disabling warning 42 makes sense for most use cases, so I'll add it to the list of the disabled warnings.

**Comment by tmattio** [comment]
For native templates, I'm thinking of adding a `dune` file at the root of the project with the following:
```
(env
 (dev
  (flags (:standard -w +A-48-42 -warn-error +A-3-44)))
 (release
  (flags (:standard -O3))))
```

If users want to opt-out, they can simply delete this file or update it. What do you think?

**Comment by johnridesabike** [comment]
That looks good to me.
