### ISSUE TITLE
Support Nix as a package manager in every template

### ISSUE THREAD

**Issue by tmattio** [tmattio/spin#83]

**Comment by citizen428** [comment]
Can you please add a bit more info in the description? I might be able to help with this.

**Comment by tmattio** [comment]
I'm not familiar with Nix, so this was mostly an exploration issue on my side. But from what I understand, Nix is a package manager that could replace Esy or Opam to fetch the dependencies, so the goal would be to offer Nix as an alternative to the currently supported package managers (Esy and Opam).

I'm not sure if that makes sense?

The setup could be inspired by anmonteiro's packages, which all use Nix. For instance: https://github.com/anmonteiro/piaf

**Comment by citizen428** [comment]
In the case you linked Nix is not used to install the package, but to make it easier to hack on, see https://github.com/anmonteiro/piaf#option-1-setting-up-the-sandbox. 😃 `nix-shell` drops the user in a new shell, that will be configured (packages installed without interfering with the user's system etc.) according to `nix/default.nix` and the other files it sources.
