### ISSUE TITLE
Running fresh template

### ISSUE THREAD

**Issue by idkjs** [tmattio/spin#84]
Running the suggested `esy install` command gets you

```shell
info esy 0.6.6 (using esy.json)
File "test/dune", line 6, characters 2-25:
6 |   (pps ppx-enumerate.lib))
      ^^^^^^^^^^^^^^^^^^^^^^^
Warning: .merlin generated is inaccurate. Cannot mix preprocessed and non
preprocessed specifications.
Split the stanzas into different directories or silence this warning by
adding (allow_approximate_merlin) to your dune-project.
```

Maybe its not important but wanted to let you know.

This seemed to help https://github.com/tmattio/spin/issues/72#issuecomment-615898220

**Comment by tmattio** [comment]
Hey @idkjs! Sorry for the late answer.

I've added a configuration in the `dune-project` for this. I'm not convinced adding this is the way to go, but it does not seem to hurt.

Thanks for reporting the issue 🙂
